name: NewTag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: Build
        run: mkdir -p bin;
          go build -o ./bin -v ./...

      - name: Archive builded binary
        uses: actions/upload-artifact@v3
        with:
          name: release-binary
          path: bin/cmd
  create-tag:
    name: Publish binaries
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-binary

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/PaaS_ClientSide/PaaS_ClientSide/bin/cmd
          asset_name: cmd
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release"